### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hista** [OkYk/okcupgrade#1]
Hi, 
Your project seems interesting, could you please add some documentation to explain how to try it?
Best regards

**Comment by OkYk** [comment]
hi @hista . its a UserScript for browser extensions tampermonkey (chrome) or greasemonkey (firefox). 
Install the script, go to the page (/doubletake for example), ensure script is running (refresh if needed), have profiles "pass" button auto-pressed if keyword from the script list is detected.
